/* ============================================================
   RECIPE DATABASE
   ------------------------------------------------------------
   Edit this file to add, remove, or tweak recipes.

   Fields:
   - id: unique slug
   - name: display name
   - category: "pasta" | "chicken" | "egg" | "toastie"
   - slot: array of meal slots this fits — "lunch" and/or "dinner"
   - blockColor: which frost-block colour token to render it as
   - freezerBlock: true if this is a batch-and-freeze recipe
   - blurb: one-line description
   - ingredients: [{ name, qty }] — plain amounts only, no prices,
     no prep method (no "diced"/"grated"/"sliced" etc. in qty —
     that goes in the matching step instead, so the shopping-list
     text stays short)
   - steps: short method
   - tags: ingredient tags used by the AVOID_TAGS filter below

   AVOID_TAGS
   ------------------------------------------------------------
   Any recipe carrying one of these tags is automatically hidden
   from the shuffle and the library. Add to this list any time a
   new disliked ingredient comes up — nothing else needs to change.
   Smooth/blended tomato (tag "tomato-smooth") is kept separate
   from raw/chunky tomato ("tomato-chunk") since blended sauce is
   fine, chunks are not.
============================================================= */

const AVOID_TAGS = ["pepper-chunk", "tomato-chunk", "fresh-fruit-chunk"];

const RECIPES = [
  // ---------------- PASTA ----------------
  {
    id: "pasta-sauce-blocks",
    name: "Frozen Tomato & Herb Sauce Blocks",
    category: "pasta",
    slot: ["dinner"],
    blockColor: "oxblood",
    freezerBlock: true,
    blurb: "The original — a big batch of smooth blended sauce, frozen in blocks, cut fresh chicken to match each night.",
    ingredients: [
      { name: "Passata", qty: "1500g" },
      { name: "Tomato purée", qty: "2 tbsp" },
      { name: "Onion", qty: "2" },
      { name: "Garlic", qty: "4 cloves" },
      { name: "Dried Italian herbs", qty: "2 tbsp" },
      { name: "Stock cube (chicken or veg)", qty: "1" },
      { name: "Olive oil", qty: "for frying" },
      { name: "Chicken breast", qty: "2" },
      { name: "Pasta", qty: "150g" },
    ],
    steps: [
      "Finely dice the onion, soften it with the garlic in oil, then add passata, purée, herbs, and crumbled stock cube.",
      "Simmer 20 minutes, then blend completely smooth with a stick blender.",
      "Cool, pour into a muffin tin or silicone tray, and freeze into blocks.",
      "Bag the frozen blocks once solid — one block per portion.",
      "On the night: dice the chicken fresh, fry it, drop in a sauce block to melt through, serve over pasta.",
    ],
    tags: ["tomato-smooth"],
  },
  {
    id: "pasta-creamy-garlic-chicken",
    name: "Creamy Garlic Chicken Pasta",
    category: "pasta",
    slot: ["dinner"],
    blockColor: "cream",
    freezerBlock: true,
    blurb: "A white sauce block — garlicky, rich, freezes just as well as the tomato one.",
    ingredients: [
      { name: "Double cream", qty: "600g" },
      { name: "Garlic", qty: "5 cloves" },
      { name: "Chicken stock", qty: "200g" },
      { name: "Parmesan", qty: "80g" },
      { name: "Butter", qty: "30g" },
      { name: "Chicken breast", qty: "2" },
      { name: "Pasta", qty: "150g" },
    ],
    steps: [
      "Melt butter, sweat garlic gently (don't brown it).",
      "Add stock and cream, simmer 10 minutes until slightly thickened.",
      "Grate the parmesan and stir in off the heat, cool, then freeze in blocks.",
      "On the night: fry chicken, melt a block through it, toss with pasta.",
    ],
    tags: [],
  },
  {
    id: "pasta-pesto-chicken",
    name: "Pesto Chicken Pasta",
    category: "pasta",
    slot: ["dinner"],
    blockColor: "olive",
    freezerBlock: true,
    blurb: "Basil pesto loosened with cream, no chunky veg anywhere in it.",
    ingredients: [
      { name: "Basil pesto (jar or homemade)", qty: "200g" },
      { name: "Double cream", qty: "150g" },
      { name: "Parmesan", qty: "50g" },
      { name: "Chicken breast", qty: "2" },
      { name: "Pasta", qty: "150g" },
    ],
    steps: [
      "Warm pesto gently with cream and parmesan until smooth — don't boil.",
      "Cool and freeze in blocks.",
      "On the night: pan-fry chicken, stir the melted block through hot pasta with the chicken.",
    ],
    tags: [],
  },
  {
    id: "pasta-bolognese-blocks",
    name: "Bolognese Sauce Blocks",
    category: "pasta",
    slot: ["dinner"],
    blockColor: "rust",
    freezerBlock: true,
    blurb: "Classic mince bolognese, blended smooth before freezing so there's no chunky tomato texture.",
    ingredients: [
      { name: "Beef or chicken mince", qty: "500g" },
      { name: "Passata", qty: "700g" },
      { name: "Onion", qty: "1" },
      { name: "Garlic", qty: "3 cloves" },
      { name: "Beef stock cube", qty: "1" },
      { name: "Dried oregano", qty: "1 tbsp" },
      { name: "Pasta", qty: "150g" },
    ],
    steps: [
      "Finely dice the onion, brown the mince with onion and garlic.",
      "Add passata, stock cube, and oregano, simmer 25 minutes.",
      "Blend smooth if you want zero texture, or leave it — cool, then freeze in blocks.",
      "Reheat a block gently and serve over pasta.",
    ],
    tags: ["tomato-smooth"],
  },
  {
    id: "pasta-lemon-butter-chicken",
    name: "Lemon Butter Chicken Pasta",
    category: "pasta",
    slot: ["dinner"],
    blockColor: "mustard",
    freezerBlock: false,
    blurb: "Fresh and light, not a freezer-block one — good for a night you're not on the batch-cook cycle.",
    ingredients: [
      { name: "Chicken breast", qty: "2" },
      { name: "Butter", qty: "40g" },
      { name: "Lemon", qty: "1" },
      { name: "Garlic", qty: "2 cloves" },
      { name: "Chicken stock", qty: "100g" },
      { name: "Pasta", qty: "150g" },
    ],
    steps: [
      "Pan-fry chicken until golden, set aside.",
      "In the same pan, melt butter with garlic, the juice of the lemon, and stock.",
      "Slice chicken back in, toss with cooked pasta.",
    ],
    tags: [],
  },
  {
    id: "pasta-cheesy-bacon-bake",
    name: "Cheesy Bacon Pasta Bake",
    category: "pasta",
    slot: ["dinner"],
    blockColor: "cream",
    freezerBlock: true,
    blurb: "A smooth cheese sauce block with bacon bits stirred through — bake it off or just melt through the pan.",
    ingredients: [
      { name: "Cheddar", qty: "200g" },
      { name: "Milk", qty: "500g" },
      { name: "Butter", qty: "30g" },
      { name: "Flour", qty: "30g" },
      { name: "Bacon", qty: "150g" },
      { name: "Pasta", qty: "150g" },
    ],
    steps: [
      "Make a roux with butter and flour, whisk in milk until smooth.",
      "Grate the cheddar and melt it in, dice and cook the bacon, stir it through.",
      "Cool and freeze in blocks, or bake fresh with pasta under the grill.",
    ],
    tags: [],
  },
  {
    id: "pasta-sausage-cream",
    name: "Sausage & Herb Cream Pasta",
    category: "pasta",
    slot: ["dinner"],
    blockColor: "rust",
    freezerBlock: true,
    blurb: "Sausage meat squeezed from the casing, browned, then a smooth herby cream sauce block.",
    ingredients: [
      { name: "Sausages", qty: "6" },
      { name: "Double cream", qty: "400g" },
      { name: "Chicken stock", qty: "150g" },
      { name: "Dried thyme", qty: "1 tsp" },
      { name: "Garlic", qty: "2 cloves" },
      { name: "Pasta", qty: "150g" },
    ],
    steps: [
      "Squeeze the sausage meat out of its casing, brown it with garlic, breaking it into small pieces.",
      "Add cream, stock, and thyme, simmer 10 minutes.",
      "Cool and freeze in blocks; reheat gently and toss with pasta.",
    ],
    tags: [],
  },
  {
    id: "pasta-teriyaki-chicken",
    name: "Teriyaki Chicken Pasta",
    category: "pasta",
    slot: ["dinner"],
    blockColor: "olive",
    freezerBlock: true,
    blurb: "A sticky, savoury-sweet sauce block that works surprisingly well over pasta instead of rice.",
    ingredients: [
      { name: "Soy sauce", qty: "100g" },
      { name: "Honey", qty: "3 tbsp" },
      { name: "Garlic", qty: "2 cloves" },
      { name: "Ginger", qty: "1 tsp" },
      { name: "Cornflour", qty: "1 tsp" },
      { name: "Chicken breast", qty: "2" },
      { name: "Pasta", qty: "150g" },
    ],
    steps: [
      "Grate the ginger, simmer soy, honey, garlic, and ginger with a cornflour slurry until glossy and thickened.",
      "Cool and freeze in blocks.",
      "Fry fresh chicken, melt the block through it, serve over pasta.",
    ],
    tags: [],
  },

  // ---------------- CHICKEN (mains, no pasta) ----------------
  {
    id: "chicken-garlic-butter",
    name: "Garlic Butter Chicken Thighs",
    category: "chicken",
    slot: ["dinner"],
    blockColor: "mustard",
    freezerBlock: false,
    blurb: "Simple pan-fried thighs finished in garlic butter — good with rice or bread on the side.",
    ingredients: [
      { name: "Chicken thighs", qty: "6" },
      { name: "Butter", qty: "40g" },
      { name: "Garlic", qty: "3 cloves" },
      { name: "Dried thyme", qty: "1 tsp" },
    ],
    steps: [
      "Pan-fry chicken thighs skin-side down until golden and cooked through.",
      "Add butter, garlic, and thyme to the pan, baste the chicken for 2 minutes.",
    ],
    tags: [],
  },
  {
    id: "chicken-honey-mustard",
    name: "Honey Mustard Chicken",
    category: "chicken",
    slot: ["dinner"],
    blockColor: "mustard",
    freezerBlock: false,
    blurb: "Sweet, tangy, and quick — one pan, one glaze.",
    ingredients: [
      { name: "Chicken breast", qty: "4" },
      { name: "Honey", qty: "3 tbsp" },
      { name: "Wholegrain or Dijon mustard", qty: "2 tbsp" },
      { name: "Butter", qty: "20g" },
    ],
    steps: [
      "Pan-fry chicken until nearly cooked through.",
      "Add honey, mustard, and butter, simmer until the sauce coats the chicken.",
    ],
    tags: [],
  },
  {
    id: "chicken-sticky-bbq",
    name: "Sticky BBQ Chicken",
    category: "chicken",
    slot: ["dinner"],
    blockColor: "oxblood",
    freezerBlock: true,
    blurb: "A smoky-sweet glaze that freezes well as a block — good over rice, in a wrap, or on its own.",
    ingredients: [
      { name: "BBQ sauce", qty: "200g" },
      { name: "Honey", qty: "2 tbsp" },
      { name: "Smoked paprika", qty: "1 tsp" },
      { name: "Chicken thighs or breast", qty: "4" },
    ],
    steps: [
      "Simmer BBQ sauce, honey, and paprika together for 5 minutes.",
      "Cool and freeze in blocks.",
      "Cook the chicken fresh, melt a block over it in the last few minutes.",
    ],
    tags: [],
  },
  {
    id: "chicken-fajita-strips",
    name: "Fajita-Spiced Chicken Strips (No Peppers)",
    category: "chicken",
    slot: ["dinner"],
    blockColor: "rust",
    freezerBlock: false,
    blurb: "All the fajita spice, none of the peppers — just seasoned chicken strips, great in a wrap.",
    ingredients: [
      { name: "Chicken breast", qty: "3" },
      { name: "Ground cumin", qty: "1 tsp" },
      { name: "Smoked paprika", qty: "1 tsp" },
      { name: "Garlic powder", qty: "1 tsp" },
      { name: "Chilli powder", qty: "pinch" },
      { name: "Oil", qty: "for frying" },
    ],
    steps: [
      "Slice the chicken into strips and toss in the spice mix.",
      "Fry hot and fast until charred at the edges and cooked through.",
    ],
    tags: [],
  },
  {
    id: "chicken-goujons",
    name: "Crispy Breaded Chicken Goujons",
    category: "chicken",
    slot: ["dinner"],
    blockColor: "mustard",
    freezerBlock: false,
    blurb: "Homemade or shop-bought breaded strips — an easy low-effort night.",
    ingredients: [
      { name: "Chicken breast", qty: "3" },
      { name: "Breadcrumbs", qty: "150g" },
      { name: "Egg", qty: "1" },
      { name: "Flour", qty: "50g" },
    ],
    steps: [
      "Slice the chicken into strips. Beat the egg.",
      "Coat the strips in flour, then beaten egg, then breadcrumbs.",
      "Bake or shallow-fry until golden and cooked through.",
    ],
    tags: [],
  },
  {
    id: "chicken-cajun-rice",
    name: "Cajun Chicken Rice",
    category: "chicken",
    slot: ["dinner"],
    blockColor: "rust",
    freezerBlock: false,
    blurb: "Spiced chicken and rice, no chunky veg required.",
    ingredients: [
      { name: "Chicken breast", qty: "3" },
      { name: "Cajun seasoning", qty: "2 tbsp" },
      { name: "Rice", qty: "300g" },
      { name: "Chicken stock", qty: "600g" },
    ],
    steps: [
      "Dice the chicken, toss in Cajun seasoning, fry until browned.",
      "Add rice and stock, simmer covered until rice is cooked through.",
    ],
    tags: [],
  },
  {
    id: "chicken-teriyaki-rice",
    name: "Teriyaki Chicken Rice Bowl",
    category: "chicken",
    slot: ["dinner"],
    blockColor: "olive",
    freezerBlock: true,
    blurb: "Same teriyaki block as the pasta version, served over rice instead.",
    ingredients: [
      { name: "Soy sauce", qty: "100g" },
      { name: "Honey", qty: "3 tbsp" },
      { name: "Garlic", qty: "2 cloves" },
      { name: "Ginger", qty: "1 tsp" },
      { name: "Chicken breast", qty: "2" },
      { name: "Rice", qty: "150g" },
    ],
    steps: [
      "Grate the ginger, simmer soy, honey, garlic, and ginger to a glaze, cool, and freeze in blocks.",
      "Fry chicken fresh, melt a block through, serve over rice.",
    ],
    tags: [],
  },
  {
    id: "chicken-parmesan-crusted",
    name: "Parmesan-Crusted Chicken",
    category: "chicken",
    slot: ["dinner"],
    blockColor: "cream",
    freezerBlock: false,
    blurb: "A cheesy crust instead of plain breadcrumbs — pairs well with any pasta night as a change of pace.",
    ingredients: [
      { name: "Chicken breast", qty: "3" },
      { name: "Parmesan", qty: "80g" },
      { name: "Breadcrumbs", qty: "100g" },
      { name: "Egg", qty: "1" },
    ],
    steps: [
      "Finely grate the parmesan and mix it through the breadcrumbs. Beat the egg.",
      "Dip chicken in the beaten egg, then the parmesan crumb, and bake until golden and cooked through.",
    ],
    tags: [],
  },

  // ---------------- EGG (lunch wraps) ----------------
  {
    id: "egg-classic-wrap",
    name: "Classic Scrambled Egg Wrap",
    category: "egg",
    slot: ["lunch"],
    blockColor: "mustard",
    freezerBlock: true,
    blurb: "The original — eggs, cheese, and your choice of bacon or ham, batch-made and frozen.",
    ingredients: [
      { name: "Eggs", qty: "6" },
      { name: "Cheddar", qty: "150g" },
      { name: "Bacon or ham", qty: "150g" },
      { name: "Tortilla wraps", qty: "6" },
    ],
    steps: [
      "Scramble the eggs softly, cook the bacon or ham separately.",
      "Grate the cheddar. Fill each wrap with egg, cheese, and bacon/ham, roll tightly.",
      "Wrap individually in foil or cling film, freeze.",
      "Reheat from frozen in the oven or microwave.",
    ],
    tags: [],
  },
  {
    id: "egg-chorizo-wrap",
    name: "Chorizo & Egg Wrap",
    category: "egg",
    slot: ["lunch"],
    blockColor: "rust",
    freezerBlock: true,
    blurb: "Smoky chorizo instead of bacon — the oil it releases flavours the eggs as they cook.",
    ingredients: [
      { name: "Eggs", qty: "6" },
      { name: "Chorizo", qty: "150g" },
      { name: "Cheddar", qty: "100g" },
      { name: "Tortilla wraps", qty: "6" },
    ],
    steps: [
      "Dice the chorizo and fry until it releases its oil, scramble the eggs in the same pan.",
      "Grate the cheddar. Fill wraps with egg, chorizo, and cheese, roll tightly.",
      "Freeze individually wrapped, reheat from frozen.",
    ],
    tags: [],
  },
  {
    id: "egg-hashbrown-wrap",
    name: "Hash Brown & Egg Wrap",
    category: "egg",
    slot: ["lunch"],
    blockColor: "cream",
    freezerBlock: true,
    blurb: "Crispy hash browns give it a different texture to the usual soft-scramble wrap.",
    ingredients: [
      { name: "Eggs", qty: "6" },
      { name: "Hash browns", qty: "6" },
      { name: "Cheddar", qty: "120g" },
      { name: "Tortilla wraps", qty: "6" },
    ],
    steps: [
      "Scramble the eggs, cook the hash browns until crisp.",
      "Grate the cheddar. Fill wraps with egg, a crumbled hash brown, and cheese, roll tightly.",
      "Freeze individually, reheat from frozen.",
    ],
    tags: [],
  },
  {
    id: "egg-sausage-wrap",
    name: "Sausage & Egg Wrap",
    category: "egg",
    slot: ["lunch"],
    blockColor: "oxblood",
    freezerBlock: true,
    blurb: "Sausage patties instead of bacon or ham for a heartier lunch.",
    ingredients: [
      { name: "Eggs", qty: "6" },
      { name: "Sausages", qty: "6" },
      { name: "Cheddar", qty: "120g" },
      { name: "Tortilla wraps", qty: "6" },
    ],
    steps: [
      "Scramble the eggs, cook the sausages and slice them.",
      "Grate the cheddar. Fill wraps with egg, sausage, and cheese, roll tightly.",
      "Freeze individually, reheat from frozen.",
    ],
    tags: [],
  },
  {
    id: "egg-bbq-chicken-wrap",
    name: "BBQ Pulled Chicken & Egg Wrap",
    category: "egg",
    slot: ["lunch"],
    blockColor: "rust",
    freezerBlock: true,
    blurb: "Leftover roast or poached chicken pulled apart and mixed with a little BBQ sauce alongside the egg.",
    ingredients: [
      { name: "Eggs", qty: "6" },
      { name: "Cooked chicken", qty: "200g" },
      { name: "BBQ sauce", qty: "3 tbsp" },
      { name: "Cheddar", qty: "100g" },
      { name: "Tortilla wraps", qty: "6" },
    ],
    steps: [
      "Shred the chicken and toss it with BBQ sauce, scramble the eggs.",
      "Grate the cheddar. Fill wraps with egg, BBQ chicken, and cheese, roll tightly.",
      "Freeze individually, reheat from frozen.",
    ],
    tags: [],
  },
  {
    id: "egg-cheesy-beans-wrap",
    name: "Cheesy Beans & Egg Wrap",
    category: "egg",
    slot: ["lunch"],
    blockColor: "mustard",
    freezerBlock: true,
    blurb: "A smooth, saucy filling — baked beans and melted cheese alongside the scrambled egg.",
    ingredients: [
      { name: "Eggs", qty: "6" },
      { name: "Baked beans", qty: "1 tin" },
      { name: "Cheddar", qty: "120g" },
      { name: "Tortilla wraps", qty: "6" },
    ],
    steps: [
      "Scramble the eggs, warm the beans through and drain off excess sauce so the wrap doesn't go soggy.",
      "Grate the cheddar. Fill wraps with egg, beans, and cheese, roll tightly.",
      "Freeze individually, reheat from frozen.",
    ],
    tags: [],
  },
  {
    id: "egg-ham-cheese-wrap",
    name: "Ham & Cheese Scrambled Egg Wrap",
    category: "egg",
    slot: ["lunch"],
    blockColor: "cream",
    freezerBlock: true,
    blurb: "The simplest variation — good as a fallback when you want minimal prep.",
    ingredients: [
      { name: "Eggs", qty: "6" },
      { name: "Ham", qty: "150g" },
      { name: "Cheddar", qty: "150g" },
      { name: "Tortilla wraps", qty: "6" },
    ],
    steps: [
      "Chop the ham. Scramble the eggs with the ham stirred through.",
      "Grate the cheddar. Fill wraps with egg mix and cheese, roll tightly.",
      "Freeze individually, reheat from frozen.",
    ],
    tags: [],
  },
  {
    id: "egg-cheese-onion-wrap",
    name: "Cheese, Egg & Caramelised Onion Wrap",
    category: "egg",
    slot: ["lunch"],
    blockColor: "olive",
    freezerBlock: true,
    blurb: "Onions cooked down soft and sweet lose the raw crunch — a different flavour angle without any crisp veg texture.",
    ingredients: [
      { name: "Eggs", qty: "6" },
      { name: "Onion", qty: "2" },
      { name: "Butter", qty: "20g" },
      { name: "Cheddar", qty: "120g" },
      { name: "Tortilla wraps", qty: "6" },
    ],
    steps: [
      "Thinly slice the onion and cook it low and slow in butter for 15–20 minutes until soft, sticky, and jammy.",
      "Scramble the eggs, grate the cheddar. Fill wraps with egg, caramelised onion, and cheese, roll tightly.",
      "Freeze individually, reheat from frozen.",
    ],
    tags: [],
  },

  // ---------------- TOASTIES (lunch or dinner) ----------------
  {
    id: "toastie-ham-cheese",
    name: "Ham & Cheese Toastie",
    category: "toastie",
    slot: ["lunch", "dinner"],
    blockColor: "cream",
    freezerBlock: false,
    blurb: "The reliable one. Five minutes, no batch-cooking required.",
    ingredients: [
      { name: "Bread", qty: "2 slices" },
      { name: "Ham", qty: "2 slices" },
      { name: "Cheddar", qty: "50g" },
      { name: "Butter", qty: "for the outside" },
    ],
    steps: ["Grate the cheddar. Butter the outsides of the bread, fill with ham and cheese, toast until golden and melted."],
    tags: [],
  },
  {
    id: "toastie-chicken-cheese",
    name: "Chicken & Cheese Toastie",
    category: "toastie",
    slot: ["lunch", "dinner"],
    blockColor: "mustard",
    freezerBlock: false,
    blurb: "Good way to use up leftover cooked chicken from another night's dinner.",
    ingredients: [
      { name: "Bread", qty: "2 slices" },
      { name: "Cooked chicken", qty: "80g" },
      { name: "Cheddar", qty: "50g" },
      { name: "Butter", qty: "for the outside" },
    ],
    steps: ["Slice the chicken, grate the cheddar. Butter the outsides of the bread, fill with chicken and cheese, toast until golden and melted."],
    tags: [],
  },
  {
    id: "toastie-bacon-egg-cheese",
    name: "Bacon, Egg & Cheese Toastie",
    category: "toastie",
    slot: ["lunch", "dinner"],
    blockColor: "rust",
    freezerBlock: false,
    blurb: "A fried egg tucked inside a bacon-and-cheese toastie — filling enough for dinner.",
    ingredients: [
      { name: "Bread", qty: "2 slices" },
      { name: "Bacon", qty: "2 rashers" },
      { name: "Egg", qty: "1" },
      { name: "Cheddar", qty: "40g" },
    ],
    steps: ["Cook the bacon and fry the egg first, grate the cheddar, then layer everything inside the bread and toast until golden."],
    tags: [],
  },
  {
    id: "toastie-garlic-cheese",
    name: "Garlic Cheese Toastie",
    category: "toastie",
    slot: ["lunch", "dinner"],
    blockColor: "mustard",
    freezerBlock: false,
    blurb: "A simple garlic-butter cheese toastie, good alongside a bowl of soup.",
    ingredients: [
      { name: "Bread", qty: "2 slices" },
      { name: "Cheddar", qty: "60g" },
      { name: "Butter", qty: "20g" },
      { name: "Garlic", qty: "1 clove" },
    ],
    steps: ["Crush the garlic and mix it through the butter, grate the cheddar. Spread the garlic butter on the outsides, fill with cheese and toast until golden."],
    tags: [],
  },
  {
    id: "wrap-bbq-chicken",
    name: "BBQ Chicken Wrap",
    category: "toastie",
    slot: ["lunch", "dinner"],
    blockColor: "oxblood",
    freezerBlock: false,
    blurb: "Fresh, not frozen — quick to throw together with leftover cooked chicken.",
    ingredients: [
      { name: "Tortilla wrap", qty: "1" },
      { name: "Cooked chicken", qty: "100g" },
      { name: "BBQ sauce", qty: "1 tbsp" },
      { name: "Cheddar", qty: "40g" },
    ],
    steps: ["Slice the chicken and warm it with BBQ sauce, grate the cheddar, fill the wrap with chicken and cheese, roll and toast if you like it crisp."],
    tags: [],
  },
  {
    id: "wrap-buffalo-chicken",
    name: "Buffalo Chicken Wrap",
    category: "toastie",
    slot: ["lunch", "dinner"],
    blockColor: "rust",
    freezerBlock: false,
    blurb: "Hot sauce and cheese take the edge off — adjust the heat to taste.",
    ingredients: [
      { name: "Tortilla wrap", qty: "1" },
      { name: "Cooked chicken", qty: "100g" },
      { name: "Hot sauce", qty: "1 tbsp" },
      { name: "Cheddar", qty: "40g" },
    ],
    steps: ["Slice the chicken and toss it in hot sauce to taste, grate the cheddar, fill the wrap with chicken and cheese, roll and toast if you like it crisp."],
    tags: [],
  },
  {
    id: "wrap-sausage-cheese",
    name: "Sausage & Cheese Wrap",
    category: "toastie",
    slot: ["lunch", "dinner"],
    blockColor: "oxblood",
    freezerBlock: false,
    blurb: "Sliced cooked sausage and melted cheese, rolled and toasted for a crisp outside.",
    ingredients: [
      { name: "Tortilla wrap", qty: "1" },
      { name: "Sausages", qty: "2" },
      { name: "Cheddar", qty: "40g" },
    ],
    steps: ["Cook and slice the sausages, grate the cheddar. Fill the wrap with sausage and cheese, roll tightly and toast in a dry pan until crisp."],
    tags: [],
  },
  {
    id: "toastie-cheese-onion",
    name: "Cheese & Caramelised Onion Toastie",
    category: "toastie",
    slot: ["lunch", "dinner"],
    blockColor: "olive",
    freezerBlock: false,
    blurb: "Same soft, jammy onion as the egg wrap variation — no raw crunch, just sweet and savoury.",
    ingredients: [
      { name: "Bread", qty: "2 slices" },
      { name: "Onion", qty: "1" },
      { name: "Butter", qty: "20g" },
      { name: "Cheddar", qty: "60g" },
    ],
    steps: ["Thinly slice the onion and cook it low and slow in butter until soft and sticky, grate the cheddar, fill the toastie with onion and cheese, toast until golden."],
    tags: [],
  },
];
